#!/bin/bash
export PTG_TWITTER_API_KEY=....
export PTG_TWITTER_API_SECRET=....
export PTG_TWITTER_ACCESS_TOKEN=....
export PTG_TWITTER_ACCESS_TOKEN_SECRET=....
#Don't put your keys,tokens/ secretes on github :P